'use client';

import { useState } from 'react';
import { FileDown, Loader2, DownloadCloud } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { ProtectedRoute } from '@/components/ProtectedRoute';
import { DashboardLayout } from '../page';

export default function ExportsPage() {
  const [isExporting, setIsExporting] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState('');
  const [status, setStatus] = useState<string | null>(null);

  const handleExport = async () => {
    if (!selectedMonth) {
      alert('Please select a month to export.');
      return;
    }

    try {
      setIsExporting(true);
      setStatus('Generating report...');

      const res = await fetch(`http://localhost:3001/exports/monthly-pack`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${localStorage.getItem('token') || ''}`,
        },
        body: JSON.stringify({ month: selectedMonth }),
      });

      if (!res.ok) throw new Error(`Export failed: ${res.statusText}`);

      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);

      const link = document.createElement('a');
      link.href = url;
      link.download = `radiNate_report_${selectedMonth}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      setStatus('✅ Report downloaded successfully.');
    } catch (error: any) {
      console.error(error);
      setStatus(`❌ ${error.message}`);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <ProtectedRoute allowedRoles={['CMIO', 'Chief Risk Officer', 'CFO']}><DashboardLayout>
    <div className="p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold flex items-center gap-2 text-gray-800">
          <DownloadCloud className="text-green-600" />
          Monthly Exports
        </h1>
      </div>

      {/* Form Section */}
      <div className="bg-white shadow rounded-lg p-6 max-w-lg mx-auto">
        <h2 className="text-lg font-semibold mb-4 text-gray-700">
          📦 Generate Monthly Report Pack
        </h2>
        <p className="text-sm text-gray-500 mb-6">
          Export includes performance metrics, drift signals, and fairness metrics as CSV/PDF files.
        </p>

        <div className="flex flex-col space-y-4">
          {/* Month selector */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Select Month
            </label>
            <input
              type="month"
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="border border-gray-300 rounded-md p-2 w-full focus:ring-2 focus:ring-green-500 outline-none"
            />
          </div>

          {/* Export button */}
          <button
            onClick={handleExport}
            disabled={isExporting}
            className={`flex items-center justify-center gap-2 px-4 py-2 rounded-md text-white font-medium transition ${
              isExporting
                ? 'bg-gray-400 cursor-not-allowed'
                : 'bg-green-600 hover:bg-green-700'
            }`}
          >
            {isExporting ? (
              <>
                <Loader2 className="animate-spin" /> Generating...
              </>
            ) : (
              <>
                <FileDown /> Download Report Pack
              </>
            )}
          </button>
        </div>

        {/* Status */}
        {status && (
          <div
            className={`mt-4 text-sm font-medium ${
              status.startsWith('✅')
                ? 'text-green-600'
                : status.startsWith('❌')
                ? 'text-red-600'
                : 'text-gray-600'
            }`}
          >
            {status}
          </div>
        )}
      </div>

      {/* Info section */}
      <div className="mt-10 text-sm text-gray-500 text-center">
        <p>
          Reports are generated by RadiNate backend based on the most recent job and metric data.
        </p>
        <p className="mt-1">
          Accessible to roles: <b>CMIO, Chief Risk Officer, CFO</b>
        </p>
      </div>
    </div></DashboardLayout></ProtectedRoute>
  );
}

// import { BackHeader } from '@/components/BackHeader';
// import { DashboardLayout } from '../page';
// import { ExportPanel } from '@/components/ExportPanel';
// import { ProtectedRoute } from '@/components/ProtectedRoute';

// export default function ExportsPage() {
//   return (
//     <>
//     <ProtectedRoute allowedRoles={["CFO", "CMIO"]}>
//       <DashboardLayout> 
//     {/* <BackHeader label="Back to Dashboard" /> */}
//     <div className="p-6 space-y-6">
//        <h1 className="text-2xl font-bold mb-4">Exports Center</h1>
//         <p className="text-gray-600">Download monthly reports and metrics ZIP packages.</p>
//       <ExportPanel />
//     </div>
//     </DashboardLayout>
//     </ProtectedRoute>
//     </>
//   );
// }
